export const PRODUCT_LIST_REQUEST_INITIATE = 'PRODUCT_LIST_REQUEST_INITIATE'
export const PRODUCT_LIST_REQUEST_SUCCESS = 'PRODUCT_LIST_REQUEST_SUCCESS'
export const PRODUCT_LIST_REQUEST_FAIL = 'PRODUCT_LIST_REQUEST_FAIL'

export const PRODUCT_REQUEST_INITIATE = 'PRODUCT_REQUEST_INITIATE'
export const PRODUCT_REQUEST_SUCCESS = 'PRODUCT_REQUEST_SUCCESS'
export const PRODUCT_REQUEST_FAIL = 'PRODUCT_REQUEST_FAIL'
